In [1]:
import pandas as pd
pd.set_option("mode.copy_on_write", True)

In [3]:
sales = pd.DataFrame(
    data={
        "employee": [
            "Katrina",
            "Guanyu",
            "Jan",
            "Roman",
            "Jacqueline",
            "Paola",
            "Esperanza",
            "Alaina",
            "Egweyn",
        ],
        "sales": [14, 17, 6, 12, 8, 3, 7, 15, 5],
        "year": [2018, 2019, 2020, 2018, 2020, 2019, 2019, 2020, 2020],
    }
)
print(sales)

     employee  sales  year
0     Katrina     14  2018
1      Guanyu     17  2019
2         Jan      6  2020
3       Roman     12  2018
4  Jacqueline      8  2020
5       Paola      3  2019
6   Esperanza      7  2019
7      Alaina     15  2020
8      Egweyn      5  2020

In [9]:
sales.query("(sales > 13 and year == 2018)")
# these same queries could have been accomplished using selection and filtering concept we discussed earlier, as shown below, but requiring more sytax

  employee  sales  year
0  Katrina     14  2018

In [6]:
sales[(sales["sales"] > 13) & (sales["year"] == 2018)]

  employee  sales  year
0  Katrina     14  2018

In [10]:
# Another nice feature of query is that we can bring in variables from our local workspace, but outside of the DataFrame by prefixing the @ symbol to the variable name.
revenue_per_sale = 1000
sales.query("sales * @revenue_per_sale > 10000")

  employee  sales  year
0  Katrina     14  2018
1   Guanyu     17  2019
3    Roman     12  2018
7   Alaina     15  2020