<h3 align="left" style="color:blue">pandas</h3>

In [2]:
import pandas as pd
import numpy as np

#### DATAFRAMES (multi dimensional array)

#### 2. Load CSV to create dataframe

In [3]:
df=pd.read_csv("nba.csv")
print(df)

              Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2     John Holland  Boston Celtics      30       SG   27    6-5     205
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4    Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
454      Raul Neto       Utah Jazz      25       PG   24    6-1     179
455   Tibor Pleiss       Utah Jazz      21        C   26    7-3     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
452           Kentucky  2239800.0
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0

[457 rows x 9 columns]

#### SELECTION & SLICING

### Indexing

In [4]:
df1=df.set_index("Name")
df1.head()

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0,PG,25,6-2,180,Texas,7730337.0
Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117.0
John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,NaN
R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,NaN,5000000.0

In [5]:
df1.reset_index(inplace=True)
df1.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,NaN,5000000.0

In [8]:
df[df.index==3]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640.0

In [9]:
df[df.index.isin(range(2,10))]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90,PF,29,6-9,240,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55,PF,21,6-8,235,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41,C,25,7-0,238,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12,PG,22,6-2,190,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36,PG,22,6-4,220,Oklahoma State,3431040.0

### Filter rows

#### 1. Row number indexing

In [11]:
print("1",df.iloc[0])                              # iloc search based on index
print('\n\n')
print("2",df.iloc[0:2])

1 Name         Avery Bradley
Team        Boston Celtics
Number                   0
Position                PG
Age                     25
Height                 6-2
Weight                 180
College              Texas
Salary           7730337.0
Name: 0, dtype: object



2             Name            Team  Number Position  Age Height  Weight  \
0  Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1    Jae Crowder  Boston Celtics      99       SF   25    6-6     235

     College     Salary
0      Texas  7730337.0
1  Marquette  6796117.0

#### 2. Row number using index values

In [12]:
df_new7=df.set_index("Name")
print('1',df_new7.loc['John Holland'])                                     # loc search based on labels
print('\n\n')
print('2',df_new7.loc['Avery Bradley':'James Young'])
print('\n\n')
print('3',df_new7.loc[['John Holland','Avery Bradley']])

1 Team           Boston Celtics
Number                     30
Position                   SG
Age                        27
Height                    6-5
Weight                    205
College     Boston University
Salary                    NaN
Name: John Holland, dtype: object



2                            Team  Number Position  Age Height  Weight  \
Name
Avery Bradley    Boston Celtics       0       PG   25    6-2     180
Jae Crowder      Boston Celtics      99       SF   25    6-6     235
John Holland     Boston Celtics      30       SG   27    6-5     205
R.J. Hunter      Boston Celtics      28       SG   22    6-5     185
Jonas Jerebko    Boston Celtics       8       PF   29   6-10     231
Amir Johnson     Boston Celtics      90       PF   29    6-9     240
Jordan Mickey    Boston Celtics      55       PF   21    6-8     235
Kelly Olynyk     Boston Celtics      41        C   25    7-0     238
Terry Rozier     Boston Celtics      12       PG   22    6-2     190
Marcus Smart     Boston Celtics      36       PG   22    6-4     220
Jared Sullinger  Boston Celtics       7        C   24    6-9     260
Isaiah Thomas    Boston Celtics       4       PG   27    5-9     185
Evan Turner      Boston Celtics      11       SG   27    6-7     220
James Young      Boston Celtics      13       SG   20    6-6     215

                           College      Salary
Name
Avery Bradley                Texas   7730337.0
Jae Crowder              Marquette   6796117.0
John Holland     Boston University         NaN
R.J. Hunter          Georgia State   1148640.0
Jonas Jerebko                  NaN   5000000.0
Amir Johnson                   NaN  12000000.0
Jordan Mickey                  LSU   1170960.0
Kelly Olynyk               Gonzaga   2165160.0
Terry Rozier            Louisville   1824360.0
Marcus Smart        Oklahoma State   3431040.0
Jared Sullinger         Ohio State   2569260.0
Isaiah Thomas           Washington   6912869.0
Evan Turner             Ohio State   3425510.0
James Young               Kentucky   1749840.0



3                          Team  Number Position  Age Height  Weight  \
Name
John Holland   Boston Celtics      30       SG   27    6-5     205
Avery Bradley  Boston Celtics       0       PG   25    6-2     180

                         College     Salary
Name
John Holland   Boston University        NaN
Avery Bradley              Texas  7730337.0

#### 3. Access data using Boolean indexing

In [19]:
attendance = pd.Series(
    [132, 94, 112, 84, 254, 322, 472],
    index=[
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
    ],
)

busy=attendance>100
print(busy)
attendance.loc[busy]

Monday        True
Tuesday      False
Wednesday     True
Thursday     False
Friday        True
Saturday      True
Sunday        True
dtype: bool

Monday       132
Wednesday    112
Friday       254
Saturday     322
Sunday       472
dtype: int64

#### Select / Extract columns

In [26]:
df1=df[["Name","Team","Age"]]
print(df1)

              Name            Team  Age
0    Avery Bradley  Boston Celtics   25
1      Jae Crowder  Boston Celtics   25
2     John Holland  Boston Celtics   27
3      R.J. Hunter  Boston Celtics   22
4    Jonas Jerebko  Boston Celtics   29
..             ...             ...  ...
452     Trey Lyles       Utah Jazz   20
453   Shelvin Mack       Utah Jazz   26
454      Raul Neto       Utah Jazz   24
455   Tibor Pleiss       Utah Jazz   26
456    Jeff Withey       Utah Jazz   26

[457 rows x 3 columns]

In [28]:
df2=df[df.columns[0:2]]
print(df2)

              Name            Team
0    Avery Bradley  Boston Celtics
1      Jae Crowder  Boston Celtics
2     John Holland  Boston Celtics
3      R.J. Hunter  Boston Celtics
4    Jonas Jerebko  Boston Celtics
..             ...             ...
452     Trey Lyles       Utah Jazz
453   Shelvin Mack       Utah Jazz
454      Raul Neto       Utah Jazz
455   Tibor Pleiss       Utah Jazz
456    Jeff Withey       Utah Jazz

[457 rows x 2 columns]

In [27]:
df3=df.loc[0:10,['Name','Team','Age']]
print(df3)

               Name            Team  Age
0     Avery Bradley  Boston Celtics   25
1       Jae Crowder  Boston Celtics   25
2      John Holland  Boston Celtics   27
3       R.J. Hunter  Boston Celtics   22
4     Jonas Jerebko  Boston Celtics   29
5      Amir Johnson  Boston Celtics   29
6     Jordan Mickey  Boston Celtics   21
7      Kelly Olynyk  Boston Celtics   25
8      Terry Rozier  Boston Celtics   22
9      Marcus Smart  Boston Celtics   22
10  Jared Sullinger  Boston Celtics   24

In [30]:
df4=df[df.Team=='Boston Celtics']
print(df4)

               Name            Team  Number Position  Age Height  Weight  \
0     Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1       Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2      John Holland  Boston Celtics      30       SG   27    6-5     205
3       R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4     Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
5      Amir Johnson  Boston Celtics      90       PF   29    6-9     240
6     Jordan Mickey  Boston Celtics      55       PF   21    6-8     235
7      Kelly Olynyk  Boston Celtics      41        C   25    7-0     238
8      Terry Rozier  Boston Celtics      12       PG   22    6-2     190
9      Marcus Smart  Boston Celtics      36       PG   22    6-4     220
10  Jared Sullinger  Boston Celtics       7        C   24    6-9     260
11    Isaiah Thomas  Boston Celtics       4       PG   27    5-9     185
12      Evan Turner  Boston Celtics      11       SG   27    6-7     220
13      James Young  Boston Celtics      13       SG   20    6-6     215
14     Tyler Zeller  Boston Celtics      44        C   26    7-0     253

              College      Salary
0               Texas   7730337.0
1           Marquette   6796117.0
2   Boston University         NaN
3       Georgia State   1148640.0
4                 NaN   5000000.0
5                 NaN  12000000.0
6                 LSU   1170960.0
7             Gonzaga   2165160.0
8          Louisville   1824360.0
9      Oklahoma State   3431040.0
10         Ohio State   2569260.0
11         Washington   6912869.0
12         Ohio State   3425510.0
13           Kentucky   1749840.0
14     North Carolina   2616975.0

#### Delete a column

In [31]:
df5=df3.drop(['Age'],axis=1)
print(df5)

               Name            Team
0     Avery Bradley  Boston Celtics
1       Jae Crowder  Boston Celtics
2      John Holland  Boston Celtics
3       R.J. Hunter  Boston Celtics
4     Jonas Jerebko  Boston Celtics
5      Amir Johnson  Boston Celtics
6     Jordan Mickey  Boston Celtics
7      Kelly Olynyk  Boston Celtics
8      Terry Rozier  Boston Celtics
9      Marcus Smart  Boston Celtics
10  Jared Sullinger  Boston Celtics

In [32]:
df6=df5.drop([7],axis=0)
print(df6)

               Name            Team
0     Avery Bradley  Boston Celtics
1       Jae Crowder  Boston Celtics
2      John Holland  Boston Celtics
3       R.J. Hunter  Boston Celtics
4     Jonas Jerebko  Boston Celtics
5      Amir Johnson  Boston Celtics
6     Jordan Mickey  Boston Celtics
8      Terry Rozier  Boston Celtics
9      Marcus Smart  Boston Celtics
10  Jared Sullinger  Boston Celtics

### Add a new column

#### 1. Add column using logical expression

In [38]:
df['Type']=df['Age'].apply(lambda Age:'High' if Age>25 else 'Low')
df.head(7)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Type
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,Texas,7730337.0,Low
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117.0,Low
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,NaN,High
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640.0,Low
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,NaN,5000000.0,High
5,Amir Johnson,Boston Celtics,90,PF,29,6-9,240,NaN,12000000.0,High
6,Jordan Mickey,Boston Celtics,55,PF,21,6-8,235,LSU,1170960.0,Low

#### 2. Add column manually

In [68]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}
df_gfg = pd.DataFrame(data)
address = ['NewYork', 'Chicago', 'Boston', 'Miami']

df_gfg['Address'] = address
print(df_gfg)

     Name  Height Qualification  Address
0  Pandas       1             A  NewYork
1   Geeks       2             B  Chicago
2     for       3             C   Boston
3   Geeks       4             D    Miami

#### 3. Add column using assign()

In [69]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}
df_gfg = pd.DataFrame(data)
address = ['NewYork', 'Chicago', 'Boston', 'Miami']

df_gfg = df_gfg.assign(address = ['NewYork', 'Chicago', 'Boston', 'Miami'])           # alternate 1
print(df_gfg)

     Name  Height Qualification  address
0  Pandas       1             A  NewYork
1   Geeks       2             B  Chicago
2     for       3             C   Boston
3   Geeks       4             D    Miami

#### 4. Add column using map()

In [70]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}
df_gfg = pd.DataFrame(data)
address = ['NewYork', 'Chicago', 'Boston', 'Miami']

address = {'Pandas': 'NewYork', 'Geeks': 'Chicago',                                   # alternate 2
            'for': 'Boston', 'Geeks_2': 'Miami'}
df_gfg['Address'] = df_gfg['Name'].map(address)
print(df_gfg)

     Name  Height Qualification  Address
0  Pandas       1             A  NewYork
1   Geeks       2             B  Chicago
2     for       3             C   Boston
3   Geeks       4             D  Chicago

#### 5. Add column using insert()

In [71]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}
df_gfg = pd.DataFrame(data)
address = ['NewYork', 'Chicago', 'Boston', 'Miami']

df_gfg.insert(2, "Age", [21, 23, 24, 21], True)                                       # alternate 3
print(df_gfg)

     Name  Height  Age Qualification
0  Pandas       1   21             A
1   Geeks       2   23             B
2     for       3   24             C
3   Geeks       4   21             D

#### 6. Add column using loc()

In [72]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}
df_gfg = pd.DataFrame(data)
address = ['NewYork', 'Chicago', 'Boston', 'Miami']

df_gfg.loc[df['Height'] >= 3, 'Category'] = 'Tall'                                    # alternate 4
df_gfg.loc[df['Height'] < 3, 'Category'] = 'Short'
print(df_gfg)

     Name  Height Qualification Category
0  Pandas       1             A    Short
1   Geeks       2             B    Short
2     for       3             C     Tall
3   Geeks       4             D     Tall

### Slicing using str.slice(start,stop,step)

In [39]:
df["Name (int)"]= df["Name"].str.slice(0,-2,2)
print(df.head())

            Name            Team  Number Position  Age Height  Weight  \
0  Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1    Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2   John Holland  Boston Celtics      30       SG   27    6-5     205
3    R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4  Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231

             College     Salary  Type Name (int)
0              Texas  7730337.0   Low     AeyBal
1          Marquette  6796117.0   Low      JeCod
2  Boston University        NaN  High      Jh ol
3      Georgia State  1148640.0   Low      RJ ut
4                NaN  5000000.0  High     JnsJrb

#### Slicing columns

In [97]:
df1 = pd.DataFrame({"a": [1, 2, 3, 4, 5, 6, 7], 
                    "b": [2, 3, 4, 2, 3, 4, 5], 
                    "c": [3, 4, 5, 2, 3, 4, 5], 
                    "d": [4, 5, 6, 2, 3, 4, 5], 
                    "e": [5, 6, 7, 2, 3, 4, 5]})
print(df1)

   a  b  c  d  e
0  1  2  3  4  5
1  2  3  4  5  6
2  3  4  5  6  7
3  4  2  2  2  2
4  5  3  3  3  3
5  6  4  4  4  4
6  7  5  5  5  5

In [98]:
df2 = df1.reindex(columns = ['c','b'])
print(df2)

   c  b
0  3  2
1  4  3
2  5  4
3  2  2
4  3  3
5  4  4
6  5  5

In [101]:
#df.loc[:,first:last:step]
df2 = df1.loc[:, "a":"e":2]
print(df2)

   a  c  e
0  1  3  5
1  2  4  6
2  3  5  7
3  4  2  2
4  5  3  3
5  6  4  4
6  7  5  5

In [102]:
#df.iloc[start:stop:step]
df2 = df1.iloc[:, 1:3:1]
print(df2)

   b  c
0  2  3
1  3  4
2  4  5
3  2  2
4  3  3
5  4  4
6  5  5