<h3 align="left" style="color:blue">pandas - cleaning data</h3>

In [14]:
import pandas as pd
import numpy as np

#### DATAFRAMES (multi dimensional array)

#### 2. Load CSV to create dataframe

In [15]:
df=pd.read_csv("nba.csv")
print(df)

              Name            Team  Number Position Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG  na  6-Feb     180
1      Jae Crowder  Boston Celtics      99       SF  25  6-Jun     235
2     John Holland  Boston Celtics      30       SG  27  6-May     205
3      R.J. Hunter  Boston Celtics      28       SG  22  6-May     185
4    Jonas Jerebko  Boston Celtics       8       PF  29  6-Oct     231
..             ...             ...     ...      ...  ..    ...     ...
452     Trey Lyles       Utah Jazz      41       PF  20  6-Oct     234
453   Shelvin Mack       Utah Jazz       8       PG  26  6-Mar     203
454      Raul Neto       Utah Jazz      25       PG  24  6-Jan     179
455   Tibor Pleiss       Utah Jazz      21        C  26  7-Mar     256
456    Jeff Withey       Utah Jazz      24        C  26    7-0     231

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
452           Kentucky  2239800.0
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0

[457 rows x 9 columns]

In [16]:
df.dtypes          #age is object, not numeric

Name         object
Team         object
Number        int64
Position     object
Age          object
Height       object
Weight        int64
College      object
Salary      float64
dtype: object

In [17]:
df['Age'].mean()

TypeError: Could not convert string 'na252722292921252222242727202627242821322226232821262526282730332332342524232826202628322523372525222222322424222027222520232029262924302327232536292424332431252826263230202330282633272936232927282729313839312325312423372429332523212027293631261928332125242227253230312223252730362722282525242927232430253126352335302724252731212724253324313535353127252925302533332936252523232223232620282631272430263028252829292230202523212724252125212824263223212729192231283133332928293732272431313027273022222726223024232530382134373639282329312523222424342528282828292627292323302526252927252527312830223634403828242733402734263526243530313531242422273231242727242730212831232224302726292332313030363424292233342326203026232021292623242624223025323322302434322733262023303029252828252926272121243620342123232826402021232530362529252021223527322426242438302124282427202523242723283424252423263020282324202423262328262026242626' to numeric

In [28]:
df.loc[~df['Age'].str.isnumeric(),'Age'].value_counts()

Age
na    1
Name: count, dtype: int64

In [29]:
df.loc[df['Age']=='na','Age']=np.nan               #np.nan represents missing data in a numeric series
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,NaN,6-Feb,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,6-Jun,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,6-May,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,6-May,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-Oct,231,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,6-Oct,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,6-Mar,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,6-Jan,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,7-Mar,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

In [30]:
df.loc[:,['Age']].value_counts()           # NaN is missing in output

Age
24     47
25     44
27     41
23     41
26     36
30     31
28     31
29     28
22     26
31     22
21     19
20     19
33     14
32     13
34     10
36     10
35      9
38      4
37      4
40      3
39      2
19      2
Name: count, dtype: int64

In [31]:
df.loc[:,['Age']].value_counts(dropna=False)         # NaN is now included

Age
24     47
25     44
27     41
23     41
26     36
30     31
28     31
29     28
22     26
31     22
21     19
20     19
33     14
32     13
34     10
36     10
35      9
37      4
38      4
40      3
19      2
39      2
NaN     1
Name: count, dtype: int64

In [9]:
df.loc[df.Age.isnull()]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,NaN,6-Feb,180,Texas,7730337.0

In [10]:
df.dtypes

Name         object
Team         object
Number        int64
Position     object
Age          object
Height       object
Weight        int64
College      object
Salary      float64
dtype: object

In [57]:
df['Age'].mean()

TypeError: unsupported operand type(s) for +: 'int' and 'str'

#### DATA CLEANSING

#### Drop rows with empty cells

In [7]:
df2=df.dropna()                           # dropna() returns new dataframe
# row 18, 22, 28 deleted
#df=df.dropna(inplace=True)                  # modify original dataframe
print(df2)

              Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
6    Jordan Mickey  Boston Celtics      55       PF   21    6-8     235
7     Kelly Olynyk  Boston Celtics      41        C   25    7-0     238
..             ...             ...     ...      ...  ...    ...     ...
449    Rodney Hood       Utah Jazz       5       SG   23    6-8     206
451  Chris Johnson       Utah Jazz      23       SF   26    6-6     206
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

           College     Salary
0            Texas  7730337.0
1        Marquette  6796117.0
3    Georgia State  1148640.0
6              LSU  1170960.0
7          Gonzaga  2165160.0
..             ...        ...
449           Duke  1348440.0
451         Dayton   981348.0
452       Kentucky  2239800.0
453         Butler  2433333.0
456         Kansas   947276.0

[364 rows x 9 columns]

In [12]:
df2=df.dropna(axis=1)                        #drop columns with blank values
print(df2)

              Name            Team  Number Position  Age Height  Weight
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2     John Holland  Boston Celtics      30       SG   27    6-5     205
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4    Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
454      Raul Neto       Utah Jazz      25       PG   24    6-1     179
455   Tibor Pleiss       Utah Jazz      21        C   26    7-3     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

[457 rows x 7 columns]

#### Replace all empty cells

In [15]:
df3=df.fillna(130)
print(df3)

              Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2     John Holland  Boston Celtics      30       SG   27    6-5     205
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4    Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
454      Raul Neto       Utah Jazz      25       PG   24    6-1     179
455   Tibor Pleiss       Utah Jazz      21        C   26    7-3     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University      130.0
3        Georgia State  1148640.0
4                  130  5000000.0
..                 ...        ...
452           Kentucky  2239800.0
453             Butler  2433333.0
454                130   900000.0
455                130  2900000.0
456             Kansas   947276.0

[457 rows x 9 columns]

#### Replace empty cells in specific columns

In [14]:
df4=df.fillna({"College":'not known'})
print(df4)

              Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2     John Holland  Boston Celtics      30       SG   27    6-5     205
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4    Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
454      Raul Neto       Utah Jazz      25       PG   24    6-1     179
455   Tibor Pleiss       Utah Jazz      21        C   26    7-3     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4            not known  5000000.0
..                 ...        ...
452           Kentucky  2239800.0
453             Butler  2433333.0
454          not known   900000.0
455          not known  2900000.0
456             Kansas   947276.0

[457 rows x 9 columns]

#### Replace with function value {mean(), median(), mode())

In [15]:
df.Salary.median()

2839073.0

In [7]:
new4_df=df.fillna({
    "Salary":df["Salary"].median()
})
print(new4_df)                                     # index 2 Salary replaced with median

              Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2     John Holland  Boston Celtics      30       SG   27    6-5     205
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4    Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
454      Raul Neto       Utah Jazz      25       PG   24    6-1     179
455   Tibor Pleiss       Utah Jazz      21        C   26    7-3     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University  2839073.0
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
452           Kentucky  2239800.0
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0

[457 rows x 9 columns]

#### Correct Date format

#### Replacing values

In [12]:
new4_df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,TX,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,2839073.0
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,TX,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,6-10,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,6-3,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,6-1,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,7-3,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

#### Replace with .loc()

In [18]:
new4_df.loc[4, 'College'] = 'Texas'                # replace fixed value
print(new4_df)

              Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2     John Holland  Boston Celtics      30       SG   27    6-5     205
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4    Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
454      Raul Neto       Utah Jazz      25       PG   24    6-1     179
455   Tibor Pleiss       Utah Jazz      21        C   26    7-3     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

               College     Salary
0                   TX  7730337.0
1            Marquette  6796117.0
2    Boston University  2839073.0
3        Georgia State  1148640.0
4                Texas  5000000.0
..                 ...        ...
452                 KT  2239800.0
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456                 KN   947276.0

[457 rows x 9 columns]

#### Replace with replace() individual values

In [19]:
new4_df['College']=new4_df['College'].replace('Texas','TX')
new4_df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,TX,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,2839073.0
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,TX,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,6-10,234,KT,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,6-3,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,6-1,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,7-3,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,KN,947276.0

#### Replace with replace() dictionary

In [20]:
values={
    'Kentucky':'KT',
    'Kansas':'KN'
}
new4_df['College']=new4_df['College'].replace(values)
new4_df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,TX,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,2839073.0
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,TX,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,6-10,234,KT,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,6-3,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,6-1,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,7-3,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,KN,947276.0

#### Replace with replace() regex

In [22]:
new4_df['Name']=new4_df['Name'].replace('\.','',regex=True)
new4_df

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
C:\Users\rajes\AppData\Local\Temp\ipykernel_4712\207467936.py:1: SyntaxWarning: invalid escape sequence '\.'
  new4_df['Name']=new4_df['Name'].replace('\.','',regex=True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,TX,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,2839073.0
3,RJ Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,TX,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,6-10,234,KT,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,6-3,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,6-1,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,7-3,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,KN,947276.0

#### Using string methods

In [23]:
new4_df['Name']=new4_df['Name'].str.upper()
new4_df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,AVERY BRADLEY,Boston Celtics,0,PG,25,6-2,180,TX,7730337.0
1,JAE CROWDER,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117.0
2,JOHN HOLLAND,Boston Celtics,30,SG,27,6-5,205,Boston University,2839073.0
3,RJ HUNTER,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640.0
4,JONAS JEREBKO,Boston Celtics,8,PF,29,6-10,231,TX,5000000.0
...,...,...,...,...,...,...,...,...,...
452,TREY LYLES,Utah Jazz,41,PF,20,6-10,234,KT,2239800.0
453,SHELVIN MACK,Utah Jazz,8,PG,26,6-3,203,Butler,2433333.0
454,RAUL NETO,Utah Jazz,25,PG,24,6-1,179,NaN,900000.0
455,TIBOR PLEISS,Utah Jazz,21,C,26,7-3,256,NaN,2900000.0
456,JEFF WITHEY,Utah Jazz,24,C,26,7-0,231,KN,947276.0

#### Identify duplicate rows

In [18]:
df[df.duplicated()]                # identify duplicated rows

Empty DataFrame
Columns: [Name, Team, Number, Position, Age, Height, Weight, College, Salary]
Index: []

#### Removing duplicate rows

In [19]:
df.drop_duplicates(inplace=True)
print(df)

              Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2     John Holland  Boston Celtics      30       SG   27    6-5     205
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4    Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
454      Raul Neto       Utah Jazz      25       PG   24    6-1     179
455   Tibor Pleiss       Utah Jazz      21        C   26    7-3     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
452           Kentucky  2239800.0
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0

[457 rows x 9 columns]

#### Rename columns

In [22]:
df.rename(columns={'Salary':'Sal'}, inplace=True)
print(df)

              Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2     John Holland  Boston Celtics      30       SG   27    6-5     205
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4    Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
454      Raul Neto       Utah Jazz      25       PG   24    6-1     179
455   Tibor Pleiss       Utah Jazz      21        C   26    7-3     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

               College        Sal
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
452           Kentucky  2239800.0
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0

[457 rows x 9 columns]