<h3 align="left" style="color:blue">pandas</h3>

##### pandas is an open-source software library built on Python for data analysis and data manipulation. The pandas library provides data structures designed specifically to handle tabular datasets with a simplified Python API. 
##### At the core of the pandas open-source library is the DataFrame data structure for handling tabular and statistical data.

##### https://www.nvidia.com/en-au/glossary/pandas-python/

In [4]:
import pandas as pd
import numpy as np

#### DATAFRAMES (multi dimensional array)

#### 5. Load JSON to create dataframe

In [84]:
df=pd.read_json("nba.json")
print(df)

              Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2     John Holland  Boston Celtics      30       SG   27    6-5     205
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4    Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
454      Raul Neto       Utah Jazz      25       PG   24    6-1     179
455   Tibor Pleiss       Utah Jazz      21        C   26    7-3     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

               College   Salary
0                Texas  7730337
1            Marquette  6796117
2    Boston University
3        Georgia State  1148640
4                       5000000
..                 ...      ...
452           Kentucky  2239800
453             Butler  2433333
454                      900000
455                     2900000
456             Kansas   947276

[457 rows x 9 columns]

#### SELECTION & SLICING

#### Extracting rows & columns - loc()

In [43]:
df_new7=df.set_index("Name")
df_new7.head()
#df.reset_index(inplace=True)

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0,PG,25,6-2,180,Texas,7730337
Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117
John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,
R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640
Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,,5000000

In [44]:
print('1',df_new7.loc['John Holland'])                                     # loc search based on labels
print('\n\n')
print('2',df_new7.loc['Avery Bradley':'James Young'])
print('\n\n')
print('3',df_new7.loc[['John Holland','Avery Bradley']])

1 Team           Boston Celtics
Number                     30
Position                   SG
Age                        27
Height                    6-5
Weight                    205
College     Boston University
Salary
Name: John Holland, dtype: object



2                            Team  Number Position  Age Height  Weight  \
Name
Avery Bradley    Boston Celtics       0       PG   25    6-2     180
Jae Crowder      Boston Celtics      99       SF   25    6-6     235
John Holland     Boston Celtics      30       SG   27    6-5     205
R.J. Hunter      Boston Celtics      28       SG   22    6-5     185
Jonas Jerebko    Boston Celtics       8       PF   29   6-10     231
Amir Johnson     Boston Celtics      90       PF   29    6-9     240
Jordan Mickey    Boston Celtics      55       PF   21    6-8     235
Kelly Olynyk     Boston Celtics      41        C   25    7-0     238
Terry Rozier     Boston Celtics      12       PG   22    6-2     190
Marcus Smart     Boston Celtics      36       PG   22    6-4     220
Jared Sullinger  Boston Celtics       7        C   24    6-9     260
Isaiah Thomas    Boston Celtics       4       PG   27    5-9     185
Evan Turner      Boston Celtics      11       SG   27    6-7     220
James Young      Boston Celtics      13       SG   20    6-6     215

                           College    Salary
Name
Avery Bradley                Texas   7730337
Jae Crowder              Marquette   6796117
John Holland     Boston University
R.J. Hunter          Georgia State   1148640
Jonas Jerebko                        5000000
Amir Johnson                        12000000
Jordan Mickey                  LSU   1170960
Kelly Olynyk               Gonzaga   2165160
Terry Rozier            Louisville   1824360
Marcus Smart        Oklahoma State   3431040
Jared Sullinger         Ohio State   2569260
Isaiah Thomas           Washington   6912869
Evan Turner             Ohio State   3425510
James Young               Kentucky   1749840



3                          Team  Number Position  Age Height  Weight  \
Name
John Holland   Boston Celtics      30       SG   27    6-5     205
Avery Bradley  Boston Celtics       0       PG   25    6-2     180

                         College   Salary
Name
John Holland   Boston University
Avery Bradley              Texas  7730337

In [45]:
df_new7=df.set_index("Team")
df_new7.head()
df_new7.loc['Minnesota Timberwolves']                                     # loc search based on labels

,Name,Number,Position,Age,Height,Weight,College,Salary
Team,,,,,,,,
Minnesota Timberwolves,Nemanja Bjelica,88,PF,28,6-10,240,,3950001
Minnesota Timberwolves,Gorgui Dieng,5,C,26,6-11,241,Louisville,1474440
Minnesota Timberwolves,Kevin Garnett,21,PF,40,6-11,240,,8500000
Minnesota Timberwolves,Tyus Jones,1,PG,20,6-2,195,Duke,1282080
Minnesota Timberwolves,Zach LaVine,8,PG,21,6-5,189,UCLA,2148360
Minnesota Timberwolves,Shabazz Muhammad,15,SF,23,6-6,223,UCLA,2056920
Minnesota Timberwolves,Adreian Payne,33,PF,25,6-10,237,Michigan State,1938840
Minnesota Timberwolves,Nikola Pekovic,14,C,30,6-11,307,,12100000
Minnesota Timberwolves,Tayshaun Prince,12,SF,36,6-9,212,Kentucky,947276
Minnesota Timberwolves,Ricky Rubio,9,PG,25,6-4,194,,12700000
Minnesota Timberwolves,Damjan Rudez,10,SF,29,6-9,230,,1149500
Minnesota Timberwolves,Greg Smith,4,PF,25,6-10,250,Fresno State,
Minnesota Timberwolves,Karl-Anthony Towns,32,C,20,7-0,244,Kentucky,5703600
Minnesota Timberwolves,Andrew Wiggins,22,SG,21,6-8,199,Kansas,5758680

#### Extracting rows & columns - iloc()

In [49]:
print("1",df_new7.iloc[0])                              # iloc search based on index
print('\n\n')
print("2",df_new7.iloc[0:2])

1 Name        Avery Bradley
Number                  0
Position               PG
Age                    25
Height                6-2
Weight                180
College             Texas
Salary            7730337
Name: Boston Celtics, dtype: object



2                          Name  Number Position  Age Height  Weight    College  \
Team
Boston Celtics  Avery Bradley       0       PG   25    6-2     180      Texas
Boston Celtics    Jae Crowder      99       SF   25    6-6     235  Marquette

                 Salary
Team
Boston Celtics  7730337
Boston Celtics  6796117

#### Select multiple columns

In [50]:
df_new1=df[["Name","Team","Age"]]
print(df_new1)

              Name            Team  Age
0    Avery Bradley  Boston Celtics   25
1      Jae Crowder  Boston Celtics   25
2     John Holland  Boston Celtics   27
3      R.J. Hunter  Boston Celtics   22
4    Jonas Jerebko  Boston Celtics   29
..             ...             ...  ...
452     Trey Lyles       Utah Jazz   20
453   Shelvin Mack       Utah Jazz   26
454      Raul Neto       Utah Jazz   24
455   Tibor Pleiss       Utah Jazz   26
456    Jeff Withey       Utah Jazz   26

[457 rows x 3 columns]

In [51]:
df_new2=df[df.columns[0:2]]
print(df_new2)

              Name            Team
0    Avery Bradley  Boston Celtics
1      Jae Crowder  Boston Celtics
2     John Holland  Boston Celtics
3      R.J. Hunter  Boston Celtics
4    Jonas Jerebko  Boston Celtics
..             ...             ...
452     Trey Lyles       Utah Jazz
453   Shelvin Mack       Utah Jazz
454      Raul Neto       Utah Jazz
455   Tibor Pleiss       Utah Jazz
456    Jeff Withey       Utah Jazz

[457 rows x 2 columns]

In [52]:
df_new3=df.loc[0:10,['Name','Team','Age']]
print(df_new3)

               Name            Team  Age
0     Avery Bradley  Boston Celtics   25
1       Jae Crowder  Boston Celtics   25
2      John Holland  Boston Celtics   27
3       R.J. Hunter  Boston Celtics   22
4     Jonas Jerebko  Boston Celtics   29
5      Amir Johnson  Boston Celtics   29
6     Jordan Mickey  Boston Celtics   21
7      Kelly Olynyk  Boston Celtics   25
8      Terry Rozier  Boston Celtics   22
9      Marcus Smart  Boston Celtics   22
10  Jared Sullinger  Boston Celtics   24

In [53]:
df_new4=df[df.Team=='Boston Celtics']
print(df_new4)

               Name            Team  Number Position  Age Height  Weight  \
0     Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1       Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2      John Holland  Boston Celtics      30       SG   27    6-5     205
3       R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4     Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
5      Amir Johnson  Boston Celtics      90       PF   29    6-9     240
6     Jordan Mickey  Boston Celtics      55       PF   21    6-8     235
7      Kelly Olynyk  Boston Celtics      41        C   25    7-0     238
8      Terry Rozier  Boston Celtics      12       PG   22    6-2     190
9      Marcus Smart  Boston Celtics      36       PG   22    6-4     220
10  Jared Sullinger  Boston Celtics       7        C   24    6-9     260
11    Isaiah Thomas  Boston Celtics       4       PG   27    5-9     185
12      Evan Turner  Boston Celtics      11       SG   27    6-7     220
13      James Young  Boston Celtics      13       SG   20    6-6     215
14     Tyler Zeller  Boston Celtics      44        C   26    7-0     253

              College    Salary
0               Texas   7730337
1           Marquette   6796117
2   Boston University
3       Georgia State   1148640
4                       5000000
5                      12000000
6                 LSU   1170960
7             Gonzaga   2165160
8          Louisville   1824360
9      Oklahoma State   3431040
10         Ohio State   2569260
11         Washington   6912869
12         Ohio State   3425510
13           Kentucky   1749840
14     North Carolina   2616975

#### Delete a column

In [54]:
df_new5=df_new3.drop(['Age'],axis=1)
print(df_new5)

               Name            Team
0     Avery Bradley  Boston Celtics
1       Jae Crowder  Boston Celtics
2      John Holland  Boston Celtics
3       R.J. Hunter  Boston Celtics
4     Jonas Jerebko  Boston Celtics
5      Amir Johnson  Boston Celtics
6     Jordan Mickey  Boston Celtics
7      Kelly Olynyk  Boston Celtics
8      Terry Rozier  Boston Celtics
9      Marcus Smart  Boston Celtics
10  Jared Sullinger  Boston Celtics

In [55]:
df_new6=df_new5.drop([7],axis=0)
print(df_new6)

               Name            Team
0     Avery Bradley  Boston Celtics
1       Jae Crowder  Boston Celtics
2      John Holland  Boston Celtics
3       R.J. Hunter  Boston Celtics
4     Jonas Jerebko  Boston Celtics
5      Amir Johnson  Boston Celtics
6     Jordan Mickey  Boston Celtics
8      Terry Rozier  Boston Celtics
9      Marcus Smart  Boston Celtics
10  Jared Sullinger  Boston Celtics

#### Add a new column

In [103]:
def func(Age):
    if Age>25:
        return "High"
    else:
        return "Low"
df['Type']=df['Age'].apply(func)
df.head(7)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary (int),Name (int),Type
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,Texas,7730337,77303,AeyBal,Low
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117,67961,JeCod,Low
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,,,Jh ol,High
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640,11486,RJ ut,Low
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,,5000000,50000,JnsJrb,High
5,Amir Johnson,Boston Celtics,90,PF,29,6-9,240,,12000000,120000,Ai on,High
6,Jordan Mickey,Boston Celtics,55,PF,21,6-8,235,LSU,1170960,11709,Jra ik,Low

In [68]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}
df_gfg = pd.DataFrame(data)
address = ['NewYork', 'Chicago', 'Boston', 'Miami']

df_gfg['Address'] = address
print(df_gfg)

     Name  Height Qualification  Address
0  Pandas       1             A  NewYork
1   Geeks       2             B  Chicago
2     for       3             C   Boston
3   Geeks       4             D    Miami

In [69]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}
df_gfg = pd.DataFrame(data)
address = ['NewYork', 'Chicago', 'Boston', 'Miami']

df_gfg = df_gfg.assign(address = ['NewYork', 'Chicago', 'Boston', 'Miami'])           # alternate 1
print(df_gfg)

     Name  Height Qualification  address
0  Pandas       1             A  NewYork
1   Geeks       2             B  Chicago
2     for       3             C   Boston
3   Geeks       4             D    Miami

In [70]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}
df_gfg = pd.DataFrame(data)
address = ['NewYork', 'Chicago', 'Boston', 'Miami']

address = {'Pandas': 'NewYork', 'Geeks': 'Chicago',                                   # alternate 2
            'for': 'Boston', 'Geeks_2': 'Miami'}
df_gfg['Address'] = df_gfg['Name'].map(address)
print(df_gfg)

     Name  Height Qualification  Address
0  Pandas       1             A  NewYork
1   Geeks       2             B  Chicago
2     for       3             C   Boston
3   Geeks       4             D  Chicago

In [71]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}
df_gfg = pd.DataFrame(data)
address = ['NewYork', 'Chicago', 'Boston', 'Miami']

df_gfg.insert(2, "Age", [21, 23, 24, 21], True)                                       # alternate 3
print(df_gfg)

     Name  Height  Age Qualification
0  Pandas       1   21             A
1   Geeks       2   23             B
2     for       3   24             C
3   Geeks       4   21             D

In [72]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}
df_gfg = pd.DataFrame(data)
address = ['NewYork', 'Chicago', 'Boston', 'Miami']

df_gfg.loc[df['Height'] >= 3, 'Category'] = 'Tall'                                    # alternate 4
df_gfg.loc[df['Height'] < 3, 'Category'] = 'Short'
print(df_gfg)

     Name  Height Qualification Category
0  Pandas       1             A    Short
1   Geeks       2             B    Short
2     for       3             C     Tall
3   Geeks       4             D     Tall

#### Access data using Boolean indexing

In [73]:
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
		'degree': ["MBA", "BCA", "M.Tech", "MBA"],
		'score':[90, 40, 80, 98]}

df_gfg1 = pd.DataFrame(dict, index = [True, False, True, False])
print(df_gfg1)

         name  degree  score
True   aparna     MBA     90
False  pankaj     BCA     40
True   sudhir  M.Tech     80
False   Geeku     MBA     98

In [74]:
print(df_gfg1.loc[True])

        name  degree  score
True  aparna     MBA     90
True  sudhir  M.Tech     80

In [76]:
print(df_gfg1.iloc[1])

name      pankaj
degree       BCA
score         40
Name: False, dtype: object

In [79]:
df_gfg2 = pd.DataFrame(dict, index = [0, 1, 2, 3])
print(df_gfg2[[True, False, True, False]])

     name  degree  score
0  aparna     MBA     90
2  sudhir  M.Tech     80

In [80]:
print(df_gfg2['degree'] == 'BCA')

0    False
1     True
2    False
3    False
Name: degree, dtype: bool

In [82]:
print(df_gfg2['score']>75)

0     True
1    False
2     True
3     True
Name: score, dtype: bool

### Slicing using str.slice(start,stop,step)

In [91]:
df["Name (int)"]= df["Name"].str.slice(0,-2,2)
print(df.head())

            Name            Team  Number Position  Age Height  Weight  \
0  Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1    Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2   John Holland  Boston Celtics      30       SG   27    6-5     205
3    R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4  Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231

             College   Salary Salary (int) Name (int)
0              Texas  7730337        77303     AeyBal
1          Marquette  6796117        67961      JeCod
2  Boston University                            Jh ol
3      Georgia State  1148640        11486      RJ ut
4                     5000000        50000     JnsJrb

#### Slicing columns

In [97]:
df1 = pd.DataFrame({"a": [1, 2, 3, 4, 5, 6, 7], 
                    "b": [2, 3, 4, 2, 3, 4, 5], 
                    "c": [3, 4, 5, 2, 3, 4, 5], 
                    "d": [4, 5, 6, 2, 3, 4, 5], 
                    "e": [5, 6, 7, 2, 3, 4, 5]})
print(df1)

   a  b  c  d  e
0  1  2  3  4  5
1  2  3  4  5  6
2  3  4  5  6  7
3  4  2  2  2  2
4  5  3  3  3  3
5  6  4  4  4  4
6  7  5  5  5  5

In [98]:
df2 = df1.reindex(columns = ['c','b'])
print(df2)

   c  b
0  3  2
1  4  3
2  5  4
3  2  2
4  3  3
5  4  4
6  5  5

In [101]:
#df.loc[:,first:last:step]
df2 = df1.loc[:, "a":"e":2]
print(df2)

   a  c  e
0  1  3  5
1  2  4  6
2  3  5  7
3  4  2  2
4  5  3  3
5  6  4  4
6  7  5  5

In [102]:
#df.iloc[start:stop:step]
df2 = df1.iloc[:, 1:3:1]
print(df2)

   b  c
0  2  3
1  3  4
2  4  5
3  2  2
4  3  3
5  4  4
6  5  5