<h3 align="left" style="color:blue">pandas</h3>

##### pandas is an open-source software library built on Python for data analysis and data manipulation. The pandas library provides data structures designed specifically to handle tabular datasets with a simplified Python API. 
##### At the core of the pandas open-source library is the DataFrame data structure for handling tabular and statistical data.

##### https://www.nvidia.com/en-au/glossary/pandas-python/

In [3]:
import pandas as pd
import numpy as np

#### DATAFRAMES (multi dimensional array)

#### 5. Load JSON to create dataframe

In [44]:
df=pd.read_json("nba.json")
print(df)

              Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2     John Holland  Boston Celtics      30       SG   27    6-5     205
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4    Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
454      Raul Neto       Utah Jazz      25       PG   24    6-1     179
455   Tibor Pleiss       Utah Jazz      21        C   26    7-3     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

               College   Salary
0                Texas  7730337
1            Marquette  6796117
2    Boston University
3        Georgia State  1148640
4                       5000000
..                 ...      ...
452           Kentucky  2239800
453             Butler  2433333
454                      900000
455                     2900000
456             Kansas   947276

[457 rows x 9 columns]

#### Operations

In [48]:
# DataFrame.aggregate(func, axis=0, *args, **kwargs)  
df.aggregate({'Age':['sum','min'], 'Salary':['max','min']})

         Age  Salary
sum  12311.0     NaN
min     19.0
max      NaN  981348

In [109]:
df.Age.min(),df.Age.max(),df.Age.mean(),df.Age.median(),df.Age.mode()

(19,
 40,
 26.938730853391686,
 26.0,
 0    24
 Name: Age, dtype: int64)

In [112]:
df[df.Position=='PG'].Age.min(),df[df.Position=='PG'].Age.max(),df[df.Position=='PG'].Age.mean(),df[df.Position=='PG'].Age.median(),df[df.Position=='PG'].Age.mode()

(20,
 40,
 26.847826086956523,
 26.5,
 0    24
 1    27
 Name: Age, dtype: int64)

In [113]:
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [114]:
df.Age.unique()

array([25, 27, 22, 29, 21, 24, 20, 26, 28, 32, 23, 30, 33, 34, 37, 36, 31,
       38, 39, 19, 35, 40], dtype=int64)

In [115]:
df.Age.value_counts()

Age
24    47
25    45
27    41
23    41
26    36
28    31
30    31
29    28
22    26
31    22
20    19
21    19
33    14
32    13
34    10
36    10
35     9
37     4
38     4
40     3
39     2
19     2
Name: count, dtype: int64

#### Apply a function

In [40]:
def func(Age):
    if Age>25:
        return "High"
    else:
        return "Low"
df['Type']=df['Age'].apply(func)
df.head(7)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Type
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,Texas,7730337,Low
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117,Low
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,,High
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640,Low
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,,5000000,High
5,Amir Johnson,Boston Celtics,90,PF,29,6-9,240,,12000000,High
6,Jordan Mickey,Boston Celtics,55,PF,21,6-8,235,LSU,1170960,Low

In [42]:
df['Type']=df['Age'].apply(lambda Age:'High' if Age>25 else 'Low')
df.head(7)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Type
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,Texas,7730337,Low
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117,Low
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,,High
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640,Low
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,,5000000,High
5,Amir Johnson,Boston Celtics,90,PF,29,6-9,240,,12000000,High
6,Jordan Mickey,Boston Celtics,55,PF,21,6-8,235,LSU,1170960,Low