<h3 align="left" style="color:blue">Pandas</h3>

In [2]:
import pandas as pd

#### SERIES (one dimensional array)

In [7]:
a = [1, 7, 2]
myvar = pd.Series(a)
print(myvar)                    #default labels starting index 0

0    1
1    7
2    2
dtype: int64

In [10]:
a = [1, 7, 2]
myvar = pd.Series(a,index=['a','b','c'])
print(myvar)

a    1
b    7
c    2
dtype: int64

#### Series (key:value objects)

In [11]:
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)                    # keys are labels/ index

day1    420
day2    380
day3    390
dtype: int64

In [12]:
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories,index=['day1'])
print(myvar)                    # keys are labels/ index

day1    420
dtype: int64

#### DATAFRAMES (multi dimensional array)

#### 1. Create dataframe manually

In [14]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [19]:
print(df.loc[1])          # output is a panda series

calories    380
duration     40
Name: 1, dtype: int64

In [20]:
print(df.loc[[0,1]])

   calories  duration
0       420        50
1       380        40

In [21]:
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

#### Maximum rows printed

In [70]:
print("max rows:",pd.options.display.max_rows)
pd.options.display.max_rows = 65                  # increase number of max rows
print("max rows:",pd.options.display.max_rows)

max rows: 9999
max rows: 65

#### 2. Load csv to create dataframe

In [71]:
df=pd.read_csv("data.csv")
print(df)                              # if dataset more than Max_rows, pandas returns first 5 and last 5 rows
#print(df.to_string())                 # returns entire dataset

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

#### 3. . Load excel to create dataframe

In [72]:
df=pd.read_excel("data_excel.xlsx")
print(df)                              # if dataset more than Max_rows, pandas returns first 5 and last 5 rows

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

#### 4. Load Python Dictionary to create dataframe

In [73]:
data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

#### 5. Load JSON to create dataframe

In [74]:
df=pd.read_json("data.json")
print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

#### View dataframe

In [75]:
df.head()                                 # print first 5 rows

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [76]:
df.head(15)                               # print first 15 rows

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.5
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0

In [77]:
df.tail(4)                                # print last 4 rows

     Duration  Pulse  Maxpulse  Calories
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [78]:
df[:15]                                   # print first 15 rows

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.5
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0

In [79]:
df.sample(2)                              # print random 4 rows

     Duration  Pulse  Maxpulse  Calories
136        45    117       143     317.7
143        45    122       149     335.4

In [80]:
df["Pulse"]       # OR
df.Pulse[:5]
#type(df.Pulse)

0    110
1    117
2    103
3    109
4    117
Name: Pulse, dtype: int64

In [81]:
df.shape

(169, 4)

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.6 KB

#### DATA CLEANSING

In [22]:
df.imdb_rating.min(),df.imdb_rating.max(),df.imdb_rating.mean(),

(1.9, 9.3, 7.919444444444445)

In [31]:
df[df.industry=="Bollywood"].imdb_rating.min(),df[df.industry=="Bollywood"].imdb_rating.max(),df[df.industry=="Bollywood"].imdb_rating.mean()

(1.9, 8.4, 7.656250000000001)

In [32]:
df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='object')

In [34]:
df.industry.unique()

array(['Bollywood', 'Hollywood'], dtype=object)

In [36]:
df.industry.value_counts()

industry
Hollywood    20
Bollywood    17
Name: count, dtype: int64

In [41]:
df_new=df[['title','industry','imdb_rating']]
df_new[:5]

                                         title   industry  imdb_rating
0                              Pather Panchali  Bollywood          8.3
1  Doctor Strange in the Multiverse of Madness  Hollywood          7.0
2                        Thor: The Dark World   Hollywood          6.8
3                              Thor: Ragnarok   Hollywood          7.9
4                      Thor: Love and Thunder   Hollywood          6.8

In [86]:
df[(df.release_year>=2000)&(df.release_year<=2010)]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi

In [87]:
df.describe()

       release_year  imdb_rating        budget        revenue
count     37.000000    36.000000     37.000000      37.000000
mean    2007.027027     7.919444   2084.975135    4117.135135
std       17.657995     1.204947  11477.487145   16372.462682
min     1946.000000     1.900000      1.000000       3.100000
25%     2001.000000     7.800000     15.500000     263.100000
50%     2014.000000     8.100000    165.000000     701.800000
75%     2018.000000     8.400000    250.000000    2000.000000
max     2022.000000     9.300000  70000.000000  100000.000000

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         37 non-null     object
 1   industry      37 non-null     object
 2   release_year  37 non-null     int64
 3   imdb_rating   36 non-null     float64
 4   studio        34 non-null     object
 5   budget        37 non-null     float64
 6   revenue       37 non-null     float64
 7   unit          37 non-null     object
 8   currency      37 non-null     object
 9   language      37 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 3.0+ KB

In [89]:
df['age']=df['release_year'].apply(lambda x:2025-x)
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,70
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,3
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,12
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,8
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,3

In [90]:
df['age']=df.apply(lambda x:2025-x['release_year'],axis=1)
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,70
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,3
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,12
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,8
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,3

In [91]:
df['profit']=df.apply(lambda x:x['revenue']-x['budget'],axis=1)
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,70,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,3,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,12,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,8,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,3,420.0

In [92]:
df.set_index("title",inplace=True)
df.head()
#df.reset_index(inplace=True)

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,70,30000.0
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,3,754.8
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,12,479.8
Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,8,674.0
Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,3,420.0

In [100]:
df.index

Index(['Pather Panchali', 'Doctor Strange in the Multiverse of Madness',
       'Thor: The Dark World ', 'Thor: Ragnarok ', 'Thor: Love and Thunder ',
       'The Shawshank Redemption', 'Interstellar', 'The Pursuit of Happyness',
       'Gladiator', 'Titanic', 'It's a Wonderful Life', 'Avatar',
       'The Godfather', 'The Dark Knight', 'Schindler's List', 'Jurassic Park',
       'Parasite', 'Avengers: Endgame', 'Avengers: Infinity War',
       'Captain America: The First Avenger',
       'Captain America: The Winter Soldier', 'Dilwale Dulhania Le Jayenge',
       '3 Idiots', 'Kabhi Khushi Kabhie Gham', 'Bajirao Mastani ',
       'Taare Zameen Par', 'Munna Bhai M.B.B.S.', 'PK', 'Sanju',
       'The Kashmir Files', 'Bajrangi Bhaijaan', 'Race 3', 'Shershaah',
       'K.G.F: Chapter 2', 'Pushpa: The Rise - Part 1', 'RRR',
       'Baahubali: The Beginning'],
      dtype='object', name='title')

In [101]:
df.loc['Thor: The Dark World ']

industry             Hollywood
release_year              2013
imdb_rating                6.8
studio          Marvel Studios
budget                   165.0
revenue                  644.8
unit                  Millions
currency                   USD
language               English
age                         12
profit                   479.8
Name: Thor: The Dark World , dtype: object

In [102]:
df.iloc[3:4]

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,8,674.0