<h3 align="left" style="color:blue">pandas</h3>

##### pandas is an open-source software library built on Python for data analysis and data manipulation. The pandas library provides data structures designed specifically to handle tabular datasets with a simplified Python API. 
##### At the core of the pandas open-source library is the DataFrame data structure for handling tabular and statistical data.

##### https://www.nvidia.com/en-au/glossary/pandas-python/

In [1]:
import pandas as pd
import numpy as np

#### DATAFRAMES (multi dimensional array)

#### 5. Load JSON to create dataframe

In [77]:
df=pd.read_json("nba.json")
print(df)

              Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2     John Holland  Boston Celtics      30       SG   27    6-5     205
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4    Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
454      Raul Neto       Utah Jazz      25       PG   24    6-1     179
455   Tibor Pleiss       Utah Jazz      21        C   26    7-3     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

               College   Salary
0                Texas  7730337
1            Marquette  6796117
2    Boston University
3        Georgia State  1148640
4                       5000000
..                 ...      ...
452           Kentucky  2239800
453             Butler  2433333
454                      900000
455                     2900000
456             Kansas   947276

[457 rows x 9 columns]

In [79]:
df.head(15)                               # default first 5 rows

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,Texas,7730337
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,,5000000
5,Amir Johnson,Boston Celtics,90,PF,29,6-9,240,,12000000
6,Jordan Mickey,Boston Celtics,55,PF,21,6-8,235,LSU,1170960
7,Kelly Olynyk,Boston Celtics,41,C,25,7-0,238,Gonzaga,2165160
8,Terry Rozier,Boston Celtics,12,PG,22,6-2,190,Louisville,1824360
9,Marcus Smart,Boston Celtics,36,PG,22,6-4,220,Oklahoma State,3431040
10,Jared Sullinger,Boston Celtics,7,C,24,6-9,260,Ohio State,2569260
11,Isaiah Thomas,Boston Celtics,4,PG,27,5-9,185,Washington,6912869
12,Evan Turner,Boston Celtics,11,SG,27,6-7,220,Ohio State,3425510
13,James Young,Boston Celtics,13,SG,20,6-6,215,Kentucky,1749840
14,Tyler Zeller,Boston Celtics,44,C,26,7-0,253,North Carolina,2616975

In [80]:
df.tail(4)                                # default last 5 rows

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8,PG,26,6-3,203,Butler,2433333
454,Raul Neto,Utah Jazz,25,PG,24,6-1,179,,900000
455,Tibor Pleiss,Utah Jazz,21,C,26,7-3,256,,2900000
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276

In [81]:
df[:15]                                   # print first 15 rows

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,Texas,7730337
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,,5000000
5,Amir Johnson,Boston Celtics,90,PF,29,6-9,240,,12000000
6,Jordan Mickey,Boston Celtics,55,PF,21,6-8,235,LSU,1170960
7,Kelly Olynyk,Boston Celtics,41,C,25,7-0,238,Gonzaga,2165160
8,Terry Rozier,Boston Celtics,12,PG,22,6-2,190,Louisville,1824360
9,Marcus Smart,Boston Celtics,36,PG,22,6-4,220,Oklahoma State,3431040
10,Jared Sullinger,Boston Celtics,7,C,24,6-9,260,Ohio State,2569260
11,Isaiah Thomas,Boston Celtics,4,PG,27,5-9,185,Washington,6912869
12,Evan Turner,Boston Celtics,11,SG,27,6-7,220,Ohio State,3425510
13,James Young,Boston Celtics,13,SG,20,6-6,215,Kentucky,1749840
14,Tyler Zeller,Boston Celtics,44,C,26,7-0,253,North Carolina,2616975

In [82]:
df.sample(2)                              # print random 4 rows

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
298,Tim Duncan,San Antonio Spurs,21,C,40,6-11,250,Wake Forest,5250000
317,Lamar Patterson,Atlanta Hawks,13,SG,24,6-5,225,Pittsburgh,525093

In [83]:
df["Name"]       # OR
df.Name[:5]
#type(df.Pulse)

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: object

In [84]:
df.shape

(457, 9)

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    int64
 3   Position  457 non-null    object
 4   Age       457 non-null    int64
 5   Height    457 non-null    object
 6   Weight    457 non-null    int64
 7   College   457 non-null    object
 8   Salary    457 non-null    object
dtypes: int64(3), object(6)
memory usage: 32.3+ KB

In [86]:
df.describe()

           Number         Age      Weight
count  457.000000  457.000000  457.000000
mean    17.678337   26.938731  221.522976
std     15.966090    4.404016   26.368343
min      0.000000   19.000000  161.000000
25%      5.000000   24.000000  200.000000
50%     13.000000   26.000000  220.000000
75%     25.000000   30.000000  240.000000
max     99.000000   40.000000  307.000000

* count: Total number of non-null values in the column.
* mean: Average value of the column.
* std: Standard deviation, showing how spread out the values are.
* min: Minimum value in the column.
* 25%: 25th percentile (Q1).
* 50%: Median value (50th percentile).
* 75%: 75th percentile (Q3).
* max: Maximum value in the column.</h4>

In [113]:
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [114]:
df.Age.unique()

array([25, 27, 22, 29, 21, 24, 20, 26, 28, 32, 23, 30, 33, 34, 37, 36, 31,
       38, 39, 19, 35, 40], dtype=int64)

In [115]:
df.Age.value_counts()

Age
24    47
25    45
27    41
23    41
26    36
28    31
30    31
29    28
22    26
31    22
20    19
21    19
33    14
32    13
34    10
36    10
35     9
37     4
38     4
40     3
39     2
19     2
Name: count, dtype: int64