<h3 align="left" style="color:blue">pandas - data types</h3>

In [2]:
import pandas as pd
import numpy as np

#### SERIES (one dimensional array)

#### Series is an ordered collection of values, generally all the same type
#### Series are basically one-dimensional numpy arrays with lots of extra features (e.g. explicit index)

#### 1. Create Series from list

In [25]:
a = [1, 7, 2]
ser = pd.Series(data=a,name='Head')
print(ser)                    # default labels starting index 0

0    1
1    7
2    2
Name: Head, dtype: int64

#### 2. Create Series from numpy array

In [26]:
data = np.array(['a','b','c', 1,2,3])
ser = pd.Series(data,name="Head")
print(ser[3:])                  # access first 3 elements from Series

3    1
4    2
5    3
Name: Head, dtype: object

#### Define custom index to Series

In [27]:
a = [1, 7, 2]
ser = pd.Series(a,index=['a','b','c'])
print(ser['b'])               # Access element using index (label)

7

#### Convert datatype

In [29]:
a = [1, 7, 2]
ser = pd.Series(a,index=['a','b','c'])
ser=ser.astype('float64')
ser

a    1.0
b    7.0
c    2.0
dtype: float64

#### 3. Create Series from key:value objects

In [16]:
calories = {"day1": 420, "day2": 380, "day3": 390}
ser = pd.Series(calories)
print(ser)                    # keys are labels/ index

day1    420
day2    380
day3    390
dtype: int64

In [7]:
calories = {"day1": 420, "day2": 380, "day3": 390}
ser=pd.Series(calories,index=['day1'])
print(ser)                    # keys are labels/ index

day1    420
dtype: int64

#### DATAFRAMES (multi dimensional array)

#### 1. Create dataframe manually

In [7]:
data = {
  "calories": [420,380,390],
  "duration": [50,40,45]
}
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [8]:
print(df.loc[1])          # output is a panda series

calories    380
duration     40
Name: 1, dtype: int64

In [9]:
print(df.loc[[0,1]])

   calories  duration
0       420        50
1       380        40

In [10]:
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

#### Maximum rows printed

In [11]:
print("max rows:",pd.options.display.max_rows)
pd.options.display.max_rows = 65                 # increase number of max rows
print("max rows:",pd.options.display.max_rows)

max rows: 60
max rows: 65

#### 2. Load Python Dictionary to create dataframe

In [4]:
data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

#### 3. Load file (csv) to create dataframe

In [3]:
df=pd.read_csv("nba.csv")
print(df)                              # if dataset more than Max_rows, pandas returns first 5 and last 5 rows
#print(df.to_string())                 # returns entire dataset

              Name            Team  Number Position Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG  na  6-Feb     180
1      Jae Crowder  Boston Celtics      99       SF  25  6-Jun     235
2     John Holland  Boston Celtics      30       SG  27  6-May     205
3      R.J. Hunter  Boston Celtics      28       SG  22  6-May     185
4    Jonas Jerebko  Boston Celtics       8       PF  29  6-Oct     231
..             ...             ...     ...      ...  ..    ...     ...
452     Trey Lyles       Utah Jazz      41       PF  20  6-Oct     234
453   Shelvin Mack       Utah Jazz       8       PG  26  6-Mar     203
454      Raul Neto       Utah Jazz      25       PG  24  6-Jan     179
455   Tibor Pleiss       Utah Jazz      21        C  26  7-Mar     256
456    Jeff Withey       Utah Jazz      24        C  26    7-0     231

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
452           Kentucky  2239800.0
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0

[457 rows x 9 columns]

In [4]:
df1=df.set_index("Name")
df1.head()
#df.reset_index(inplace=True)

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0,PG,na,6-Feb,180,Texas,7730337.0
Jae Crowder,Boston Celtics,99,SF,25,6-Jun,235,Marquette,6796117.0
John Holland,Boston Celtics,30,SG,27,6-May,205,Boston University,NaN
R.J. Hunter,Boston Celtics,28,SG,22,6-May,185,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8,PF,29,6-Oct,231,NaN,5000000.0

In [5]:
df1.loc['John Holland']                   # loc search based on labels

Team           Boston Celtics
Number                     30
Position                   SG
Age                        27
Height                  6-May
Weight                    205
College     Boston University
Salary                    NaN
Name: John Holland, dtype: object

In [7]:
df1.iloc[0]                              # iloc search based on index

Team        Boston Celtics
Number                   0
Position                PG
Age                     na
Height               6-Feb
Weight                 180
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object

#### 4. Create DataFrame from numpy array

In [8]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df_new = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df_new)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

#### 5. Create Dataframe from Excel

In [22]:
df1=pd.read_excel("nba.xlsx",'nba (2)')
print(df1.head())

            Name            Team  Number Position  Age Height  Weight  \
0  Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1    Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2   John Holland  Boston Celtics      30       SG   27    6-5     205
3    R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4  Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

#### Object datatype is slower than integer datatype

In [9]:
import pandas as pd
import numpy as np

object_numbers = pd.Series(np.arange(1000000), dtype="object")
numbers = pd.Series(np.arange(1000000), dtype="int64")

%timeit object_numbers * 2
%timeit numbers * 2

36.8 ms ± 1.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.15 ms ± 292 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

#### Category data type

In [10]:
df.dtypes

Name         object
Team         object
Number        int64
Position     object
Age          object
Height       object
Weight        int64
College      object
Salary      float64
dtype: object

In [11]:
df['Team']=df['Team'].astype('category')

In [12]:
df.dtypes

Name          object
Team        category
Number         int64
Position      object
Age           object
Height        object
Weight         int64
College       object
Salary       float64
dtype: object

In [13]:
df['Team'].cat.categories

Index(['Atlanta Hawks', 'Boston Celtics', 'Brooklyn Nets', 'Charlotte Hornets',
       'Chicago Bulls', 'Cleveland Cavaliers', 'Dallas Mavericks',
       'Denver Nuggets', 'Detroit Pistons', 'Golden State Warriors',
       'Houston Rockets', 'Indiana Pacers', 'Los Angeles Clippers',
       'Los Angeles Lakers', 'Memphis Grizzlies', 'Miami Heat',
       'Milwaukee Bucks', 'Minnesota Timberwolves', 'New Orleans Pelicans',
       'New York Knicks', 'Oklahoma City Thunder', 'Orlando Magic',
       'Philadelphia 76ers', 'Phoenix Suns', 'Portland Trail Blazers',
       'Sacramento Kings', 'San Antonio Spurs', 'Toronto Raptors', 'Utah Jazz',
       'Washington Wizards'],
      dtype='object')

In [14]:
df['Team'].cat.codes

0       1
1       1
2       1
3       1
4       1
       ..
452    28
453    28
454    28
455    28
456    28
Length: 457, dtype: int8

In [22]:
df.loc[df['Team']=='Utah Jazz']

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
442,Trevor Booker,Utah Jazz,33,PF,28,6-8,228,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3,PG,23,6-1,191,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10,SG,24,6-6,214,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11,PG,20,6-6,190,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15,PF,24,6-10,265,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27,C,23,7-1,245,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20,SF,26,6-8,226,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5,SG,23,6-8,206,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2,SF,28,6-8,226,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23,SF,26,6-6,206,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41,PF,20,6-10,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,6-3,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,6-1,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,7-3,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0