In [54]:
import pandas as pd
import numpy as np

In [55]:
df=pd.read_stata("US_ACS_2017_10pct_sample.dta")
print(df.head())

   year  datanum   serial      cbserial          numprec subsamp  hhwt  \
0  2017        1   177686  2.017001e+12                9      64    55
1  2017        1  1200045  2.017001e+12                6      79    25
2  2017        1    70831  2.017000e+12  1 person record      36    57
3  2017        1   557128  2.017001e+12                2      10    98
4  2017        1   614890  2.017001e+12                4      96    54

                                   hhtype       cluster    adjust  ...  \
0  female householder, no husband present  2.017002e+12  1.011189  ...
1       male householder, no wife present  2.017012e+12  1.011189  ...
2          male householder, living alone  2.017001e+12  1.011189  ...
3         married-couple family household  2.017006e+12  1.011189  ...
4         married-couple family household  2.017006e+12  1.011189  ...

   migcounty1                 migmet131 vetdisab                   diffrem  \
0           0  not in identifiable area      n/a                       n/a
1           0  not in identifiable area      n/a   no cognitive difficulty
2           0  not in identifiable area      n/a  has cognitive difficulty
3           0  not in identifiable area      n/a   no cognitive difficulty
4           0  not in identifiable area      n/a                       n/a

                   diffphys                           diffmob diffcare  \
0                       n/a                               n/a      n/a
1  no ambulatory difficulty  no independent living difficulty       no
2  no ambulatory difficulty  no independent living difficulty       no
3  no ambulatory difficulty  no independent living difficulty       no
4                       n/a                               n/a      n/a

                          diffsens  diffeye  diffhear
0  no vision or hearing difficulty       no        no
1  no vision or hearing difficulty       no        no
2  no vision or hearing difficulty       no        no
3  no vision or hearing difficulty       no        no
4  no vision or hearing difficulty       no        no

[5 rows x 104 columns]

In [82]:
df.columns

Index(['year', 'datanum', 'serial', 'cbserial', 'numprec', 'subsamp', 'hhwt',
       'hhtype', 'cluster', 'adjust',
       ...
       'migcounty1', 'migmet131', 'vetdisab', 'diffrem', 'diffphys', 'diffmob',
       'diffcare', 'diffsens', 'diffeye', 'diffhear'],
      dtype='object', length=104)

In [56]:
print(df['inctot'].mean().round(2))

1723646.27

In [57]:
df['inctot'].value_counts()

inctot
9999999    53901
0          33679
30000       4778
50000       4414
40000       4413
           ...
70520          1
76680          1
57760          1
200310         1
505400         1
Name: count, Length: 8471, dtype: int64

In [58]:
df['inctot'].value_counts(normalize=True).round(3)

inctot
9999999    0.169
0          0.106
30000      0.015
50000      0.014
40000      0.014
           ...
70520      0.000
76680      0.000
57760      0.000
200310     0.000
505400     0.000
Name: proportion, Length: 8471, dtype: float64

In [59]:
df['inctot']=df['inctot'].replace(9999999,np.nan)
df['inctot'].value_counts(dropna=False,normalize=True).round(3)

inctot
NaN         0.169
0.0         0.106
30000.0     0.015
50000.0     0.014
40000.0     0.014
            ...
70520.0     0.000
76680.0     0.000
57760.0     0.000
200310.0    0.000
505400.0    0.000
Name: proportion, Length: 8471, dtype: float64

In [60]:
print(df['inctot'].mean().round(2))

40890.18

In [66]:
df[['age','inctot']].value_counts()
#df.loc[df.age==39]

age  inctot
15   0.0         3380
16   0.0         2831
17   0.0         2210
18   0.0         1665
19   0.0         1193
                 ...
54   493100.0       1
     493800.0       1
     494000.0       1
     494996.0       1
96   86400.0        1
Name: count, Length: 60852, dtype: int64

In [76]:
pd.set_option("display.max_rows", None)
df1=df[df.inctot.isnull()]
df1.age.value_counts()

age
10                           3997
9                            3977
14                           3847
12                           3845
13                           3800
11                           3791
8                            3648
7                            3527
6                            3524
5                            3512
2                            3405
1                            3340
4                            3318
3                            3220
less than 1 year old         3150
74                              0
73                              0
72                              0
71                              0
70                              0
66                              0
69                              0
68                              0
67                              0
60                              0
65                              0
64                              0
63                              0
62                              0
61                              0
76                              0
59                              0
58                              0
75                              0
83                              0
77                              0
78                              0
95                              0
94                              0
93                              0
92                              0
91                              0
90 (90+ in 1980 and 1990)       0
89                              0
88                              0
87                              0
86                              0
85                              0
84                              0
56                              0
82                              0
81                              0
80                              0
79                              0
57                              0
48                              0
55                              0
33                              0
31                              0
30                              0
29                              0
28                              0
27                              0
26                              0
25                              0
24                              0
23                              0
22                              0
21                              0
20                              0
19                              0
18                              0
17                              0
16                              0
15                              0
32                              0
34                              0
54                              0
35                              0
53                              0
52                              0
51                              0
50                              0
49                              0
47                              0
46                              0
45                              0
44                              0
43                              0
42                              0
41                              0
40                              0
39                              0
38                              0
37                              0
36                              0
96                              0
Name: count, dtype: int64

In [79]:
df1['age'].max()

'14'

In [77]:
df2=df[df.inctot.notnull()]
df2.age.value_counts()

age
60                           4950
54                           4821
59                           4776
56                           4776
58                           4734
57                           4720
55                           4693
61                           4644
62                           4614
53                           4600
18                           4496
63                           4488
52                           4418
65                           4362
19                           4342
64                           4287
50                           4272
47                           4256
66                           4106
16                           4106
46                           4064
67                           4055
51                           4021
17                           4021
20                           3992
48                           3956
70                           3953
68                           3951
34                           3942
15                           3942
49                           3940
45                           3939
30                           3917
40                           3884
27                           3884
32                           3883
31                           3880
69                           3877
37                           3870
35                           3867
36                           3834
29                           3810
28                           3808
39                           3783
26                           3781
21                           3740
33                           3734
38                           3718
25                           3708
44                           3656
24                           3641
22                           3617
42                           3603
43                           3573
23                           3551
41                           3487
71                           2917
72                           2901
74                           2819
73                           2781
75                           2532
76                           2170
77                           2089
78                           1985
79                           1758
80                           1721
81                           1524
82                           1464
83                           1335
84                           1157
85                           1117
86                           1041
94                           1035
87                            908
88                            859
89                            628
90 (90+ in 1980 and 1990)     480
93                            476
95                            471
92                            355
91                            227
96                             10
1                               0
14                              0
13                              0
12                              0
11                              0
10                              0
9                               0
8                               0
7                               0
6                               0
5                               0
4                               0
3                               0
2                               0
less than 1 year old            0
Name: count, dtype: int64

In [80]:
df1['age'].min()

'less than 1 year old'

In [81]:
df['empstat'].value_counts()

empstat
employed              148758
not in labor force    104676
n/a                    57843
unemployed              7727
Name: count, dtype: int64

In [83]:
df['race'].value_counts()

race
white                               243751
black/african american/negro         31691
other asian or pacific islander      12508
other race, nec                      12304
two major races                       8826
chinese                               4313
american indian or alaska native      3595
three or more major races             1207
japanese                               809
Name: count, dtype: int64

In [85]:
df.dtypes['race']

CategoricalDtype(categories=['white', 'black/african american/negro',
                  'american indian or alaska native', 'chinese', 'japanese',
                  'other asian or pacific islander', 'other race, nec',
                  'two major races', 'three or more major races'],
, ordered=True, categories_dtype=object)

In [115]:
df2=df[(df.race=='white')&(df.empstat=='employed')]
df2.inctot.mean().round(2)

60473.15

In [116]:
df3=df[(df.race=='black/african american/negro')&(df.empstat=='employed')]
df3.inctot.mean().round(2)

41747.95

In [117]:
((df2.inctot.mean().round(2)-df3.inctot.mean().round(2))/df2.inctot.mean().round(2)*100).round(2)

30.96

In [133]:
df4=df[['race','inctot','perwt','empstat','hispan']]
df4.head(10)

    race   inctot  perwt             empstat        hispan
0  white      NaN     84                 n/a       mexican
1  white   6000.0     57            employed         other
2  white   6150.0     58            employed  not hispanic
3  white  14000.0     98  not in labor force  not hispanic
4  white      NaN     45                 n/a  not hispanic
5  white  50000.0    195            employed  not hispanic
6  white  27100.0     56  not in labor force  not hispanic
7  white      NaN     87                 n/a       mexican
8  white      NaN    107                 n/a       mexican
9  white   2000.0     12            employed  not hispanic

In [150]:
df4['wt']=df4['inctot']*df4['perwt']
df4.head(10)

C:\Users\rajes\AppData\Local\Temp\ipykernel_9560\3065817015.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['wt']=df4['inctot']*df4['perwt']

    race   inctot  perwt             empstat        hispan         wt
0  white      NaN     84                 n/a       mexican        NaN
1  white   6000.0     57            employed         other   342000.0
2  white   6150.0     58            employed  not hispanic   356700.0
3  white  14000.0     98  not in labor force  not hispanic  1372000.0
4  white      NaN     45                 n/a  not hispanic        NaN
5  white  50000.0    195            employed  not hispanic  9750000.0
6  white  27100.0     56  not in labor force  not hispanic  1517600.0
7  white      NaN     87                 n/a       mexican        NaN
8  white      NaN    107                 n/a       mexican        NaN
9  white   2000.0     12            employed  not hispanic    24000.0

In [165]:
df5=df4[(df4.race=='white')&(df4.empstat=='employed')]
#print(df5.head(10))
(df5.wt.sum()/df5.perwt.sum()).round(2)

     race    inctot  perwt   empstat        hispan          wt
1   white    6000.0     57  employed         other    342000.0
2   white    6150.0     58  employed  not hispanic    356700.0
5   white   50000.0    195  employed  not hispanic   9750000.0
9   white    2000.0     12  employed  not hispanic     24000.0
12  white   24000.0    108  employed  not hispanic   2592000.0
16  white   75000.0     42  employed  not hispanic   3150000.0
22  white   58000.0     74  employed  not hispanic   4292000.0
23  white   52000.0     51  employed  not hispanic   2652000.0
25  white  120080.0    112  employed  not hispanic  13448960.0
35  white    4600.0     14  employed  not hispanic     64400.0

58361.48

In [157]:
df6=df4[(df4.race=='black/african american/negro')&(df4.empstat=='employed')]
(df6.wt.sum()/df6.perwt.sum()).round(2)

40430.95

In [168]:
df7=df4[(df4.race=='white')&(df4.empstat=='employed')&(df4.hispan=='not hispanic')]
#print(df7.head(10))
(df7.wt.sum()/df7.perwt.sum()).round(2)

61669.29